# version: "3.9"  # optional since v1.27.0
services:
  vdf:
    build: .
    command:
      - "--log-sink"
      - "http://seq:5341"
    ports:
      - "127.0.0.1:5000:80"
    networks: [vdf]
  seq:
    image: datalust/seq
    ports:
      - "127.0.0.1:9080:80"
    environment:
      ACCEPT_EULA: "Y"
    networks: [vdf]

networks:
  vdf:
    driver: bridge
    internal: false
    name: vdf
    ipam:
      config:
        - subnet: 172.16.57.0/24
